version: '3.8'

services:
  annvil-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3025:80"
    networks:
      - annvil-net

networks:
  annvil-net:
    driver: bridge